radio/articles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'tag/(?P<tag_name>.+)/$', views.TagDetailView.as_view(), name='tag_detail'),
    url(r'create/$', views.ArticleCreateView.as_view(), name='create_article'),
    url(r'list/$', views.ArticleListView.as_view(), name='article_list'),
    url(r'drafts/$', views.DraftArticlesListView.as_view(), name='draft_article'),
    url(r'A-(?P<slug>[-\w]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
    url(r'^comment/$', views.comment, name='comment'),
    # url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit_article'),
]

radio/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

radio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import radio.profiles.urls
import radio.accounts.urls
import radio.programs.urls
import radio.articles.urls
from . import views
from ckeditor_uploader import views as ck_views

urlpatterns = [
    url(r'^article/', include(radio.articles.urls, namespace='articles')),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^', include(radio.accounts.urls, namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(radio.profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^program/', include(radio.programs.urls, namespace='program')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ckeditor/browse/', ck_views.browse, name='ckeditor_browse'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

radio/articles/models.py
from datetime import datetime
from django.conf import  settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.contrib import admin
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from django.utils import timezone

User = settings.AUTH_USER_MODEL

class ArticleManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ArticleManager, self).all().filter(publish__lte =timezone.now().date())


class Article(models.Model):
    DRAFT = 'D'
    PUBLISHED = 'P'
    STATUS = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(editable=False, unique=True)
    content = RichTextUploadingField(max_length=10000)
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    creator = models.ForeignKey(User, null=True, blank=True)
    publish = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    updator = models.ForeignKey(User, null=True, blank=True, related_name="+")

    objects = ArticleManager()

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ("-created",)

    def get_absolute_url(self):
        return reverse('articles:article_detail', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title


    def create_slug(instance, x=2, new_slug=None,):
        slug = slugify(instance.title)
        if new_slug is not None:
            slug = new_slug
        qs = Article.objects.filter(slug=slug).order_by('-id')
        exists = qs.exists()
        if exists:
            slug = '%s-%s' % (slugify(instance.title), x)
            x += 1
            return Article.create_slug(instance, x=x, new_slug=slug)
        return slug

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = Article.create_slug(self)
            super(Article, self).save(*args, **kwargs)
        else:
            self.updated = datetime.now()
        if not self.slug:
            self.slug = Article.create_slug(self)


        super(Article, self).save(*args, **kwargs)

    @staticmethod
    def get_published():
        articles = Article.objects.filter(status=Article.PUBLISHED)
        return articles

    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(' ')
        for tag in tag_list:
            if tag:
                Tag.objects.get_or_create(tag=tag.lower(), article_id = self)

    def get_tags(self):
        return Tag.objects.filter(article=self)

    def get_summary(self):
        if len(self.content) > 255:
            return '{0}...'.format(self.content[:255])
        else:
            return self.content

    def get_comments(self):
        return ArticleComment.objects.filter(article=self)

admin.site.register(Article)


class Tag(models.Model):
    name = models.CharField(max_length=50)
    article = models.ForeignKey(Article)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')
        unique_together = (('name', 'article'),)
        index_together = [['name', 'article'], ]

    def __str__(self):
        return self.tag

    def create_tags(self, tags):
        tags = tags.strip()
        tag_list = tags.split(' ')
        for tag in tag_list:
            if tag:

                t, created = Tag.objects.get_or_create(tag=tag.lower(),
                                                       article_id = self)


    @staticmethod
    def get_popular_tags():
        tags = Tag.objects.all()
        count = {}
        for tag in tags:
            if tag.article.status == Article.PUBLISHED:
                if tag.name in count:
                    count[tag.name] = count[tag.name] + 1
                else:
                    count[tag.name] = 1
        sorted_count = sorted(count.items(), key=lambda t: t[1], reverse=True)
        return sorted_count[:20]

admin.site.register(Tag)

class ArticleComment(models.Model):
    article = models.ForeignKey(Article)
    comment = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = _("Article Comment")
        verbose_name_plural = _("Article Comments")
        ordering = ("date",)

    def __str__(self):
        return '{0} - {1}'.format(self.user.username, self.article.title)

admin.site.register(ArticleComment)

radio/articles/forms.py
from .models import Article
from ckeditor_uploader.fields import RichTextUploadingFormField
from django import forms


class ReportForm(forms.Form):
    date = forms.DateField()


class ArticleForm(forms.ModelForm):
    # status = forms.CharField(widget=forms.HiddenInput())
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=255)
    tags = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=255, required=False,
        help_text='Use spaces to separate the tags, such as "java jsf primefaces"')  # noqa: E501

    class Meta:

        model = Article
        fields = ('title', 'content', 'tags', 'publish')

radio/articles/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from .forms import ArticleForm
from .models import Article, ArticleComment, Tag
from django.views.generic import DetailView, CreateView, ListView, View
from django.urls import reverse
from django.conf import settings

User = settings.AUTH_USER_MODEL


class ArticleListView(ListView):
    model = Article
    queryset = Article.objects.all().filter(status=Article.PUBLISHED)


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('articles:article_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.creator = self.request.user
        tags = form.cleaned_data.get('tags')
        self.object.save()
        article = self.object.pk
        Article.create_tags(article, tags)
        return super(ArticleCreateView, self).form_valid(form)


class DraftArticlesListView(ListView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super(DraftArticlesListView, self).get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context['article_list'] = Article.objects.all().filter(status=Article.DRAFT)
        else:
            context['article_list'] = Article.objects.all().filter(status=Article.DRAFT, creator=self.request.user)
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'articles/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all().filter(article__slug=self.kwargs['slug'])
        return context

class TagDetailView(View):
    def get(self, request, tag_name):
        articles = Article.objects.all().filter(tag__name=tag_name, status=Article.PUBLISHED)
        return render(request, 'articles/article_list.html', {'article_list': articles})


def comment(request):
    try:
        if request.method == 'POST':
            article_id = request.POST.get('article')
            article = Article.objects.get(pk=article_id)
            comment = request.POST.get('comment')
            comment = comment.strip()
            if len(comment) > 0:
                article_comment = ArticleComment(user=request.user,
                                                 article=article,
                                                 comment=comment)
                article_comment.save()
            html = ''
            for comment in article.get_comments():
                html = '{0}{1}'.format(html, render_to_string(
                    'articles/partial_article_comment.html',
                    {'comment': comment}))

            return HttpResponse(html)

        else:
            return HttpResponseBadRequest()

    except Exception:
        return HttpResponseBadRequest()



# @login_required
# def edit(request, id):
#     tags = ''
#     if id:
#         article = get_object_or_404(Article, pk=id)
#         for tag in article.get_tags():
#             tags = '{0} {1}'.format(tags, tag.name)
#         tags = tags.strip()
#     else:
#         article = Article(creator=request.user)
#
#     if article.creator.id != request.user.id:
#         return redirect('home')
#
#     if request.POST:
#         form = ArticleForm(request.POST, instance=article)
#         if form.is_valid():
#             form.save()
#             return redirect('/articles/')
#     else:
#         form = ArticleForm(instance=article, initial={'tags': tags})
#     return render(request, 'articles/edit.html', {'form': form})
#

radio/articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ article.title }} <small>{{ article.publish }}</small> </h2>

    <hr>
    {% for tag in tags %}
        <pre><a href="{% url 'articles:tag_detail' tag.name %}">{{ tag.name }}</a></pre>
    {% endfor %}
    
    {{ article.content|safe }}
{% endblock %}

radio/articles/templates/articles/article_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load staticfiles i18n %}
{% block content %}
    <h2>Make a Payment</h2>
    <form action="" method="post" role="form">
      {% csrf_token %}
        {{ form.media }}
      {{ form|crispy }}
            <button type="submit">{% trans 'Submit' %}</button>
        <br><br>
    </form>
{% endblock content %}

radio/articles/templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
    <br><br>
    <hr>
{% for article in article_list %}
    <a href="{{ article.get_absolute_url }}">{{ article }}</a> <br>
{% endfor %}
{% endblock content %}

radio/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/articles.js' %}"></script>
{% endblock head %}

{% block content %}
  <ol class="breadcrumb">
    <li><a href="{% url 'articles:articles' %}">{% trans 'Articles' %}</a></li>
    <li><a href="{% url 'articles:drafts' %}">{% trans 'Drafts' %}</a></li>
    <li class="active">{% trans 'Edit' %}</li>
  </ol>
  <form action="{% url 'articles:edit_article' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {{ form.status }}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {% if field.label == 'Content' %}
          {% include 'markdown_editor.html' with textarea='id_content' %}
        {% endif %}
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button>
      <a href="{% url 'drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock content %}

radio/articles/templates/articles/partial_article.html
<article>
  <h2><a href="{% url 'articles:article' article.slug %}">{{ article.title }}</a></h2>
  <div class="info">
    <span class="date">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ article.create_date }}
    </span>
    <span class="user">
      <a href="{% url 'profiles:show_self' %}"><img src="{{ article.creator.profile.get_picture }}"></a>
      <a href="{% url 'profiles:show_self' %}">{{ article.creator.profile.get_screen_name }}</a>
    </span>
    <span class="comments">
      <span class="glyphicon glyphicon-comment"></span>
      {{ article.get_comments.count }} Comments
    </span>
  </div>
  <div class="content">
    {{ article.get_content_as_markdown|safe }}
  </div>
  {% if article.get_tags %}
    <div class="tags">
      {% for tag in article.get_tags %}
        <a href="{% url 'articles:tag' tag.name %}"><span class="label label-default">{{ tag }}</span></a>
      {% endfor %}
    </div>
  {% endif %}
</article>

radio/articles/templates/articles/partial_article_comment.html
{% load humanize %}
<div class="comment">
  <a href="{% url 'profiles:show_self' %}"><img src="{{ comment.user.profile.get_picture }}" class="comment-portrait"></a>
  <div class="comment-text">
    <h5>
      <a href="{% url 'profiles:show_self'  %}">{{ comment.user.profile.get_screen_name }}</a>
      <small>{{ comment.date|naturaltime }}</small>
    </h5>
    <p>{{ comment.comment }}</p>
  </div>
</div>

radio/articles/templates/articles/partial_article_comments.html
{% load i18n %}
<hr>
<span class="pull-right text-muted" id="comment-helper" style="display: none"><small>{% trans 'Press Ctrl + Enter to post' %}</small></span>
<h4><span class="comment-count">{{ article.get_comments.count }}</span> {% trans 'Comments' %}</h4>
<div class="post-comment clearfix">
  <form role="form" id="comment-form">
    {% csrf_token %}
    <input type="hidden" name="article" value="{{ article.pk }}">
    <div class="user-portrait clearfix">
      <img src="{{ user.profile.get_picture }}">
    </div>
    <div class="comment-input clearfix">
      <textarea class="form-control" rows="1" placeholder="{% trans 'Write a comment...' %}" name="comment" id="comment"></textarea>
    </div>
  </form>
</div>
<div class="well well-sm" id="comment-list">
  {% for comment in article.get_comments %}
    {% include 'articles/partial_article_comment.html' with comment=comment %}
  {% empty %}
    <div style="padding: .6em 0">{% trans 'Be the first one to comment!' %}</div>
  {% endfor %}
</div>

radio/articles/templates/articles/tag_list.html
{% extends 'base.html' %}

{% block content %}
    <br><br>
    <hr>
{% for article in tag_list %}
    <a href="{{ article.get_absolute_url }}">{{ article }}</a> <br>
{% endfor %}
{% endblock content %}